// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.6.9;

import "@openzeppelin/contracts-ethereum-package/contracts/Initializable.sol";
import "@openzeppelin/contracts-ethereum-package/contracts/access/AccessControl.sol";
import "@openzeppelin/contracts-ethereum-package/contracts/GSN/Context.sol";
import "@openzeppelin/contracts-ethereum-package/contracts/utils/Counters.sol";
import "@openzeppelin/contracts-ethereum-package/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts-ethereum-package/contracts/token/ERC721/ERC721Burnable.sol";
import "@openzeppelin/contracts-ethereum-package/contracts/token/ERC721/ERC721Pausable.sol";

/**
 * @dev {ERC721} token, including:
 *
 *  - ability for holders to burn (destroy) their tokens
 *  - a minter role that allows for token minting (creation)
 *  - a pauser role that allows to stop all token transfers
 *  - token ID and URI autogeneration
 *
 * This contract uses {AccessControl} to lock permissioned functions using the
 * different roles - head to its documentation for details.
 *
 * The account that deploys the contract will be granted the minter and pauser
 * roles, as well as the default admin role, which will let it grant both minter
 * and pauser roles to aother accounts
 */
contract DarkForestNFT is
    Initializable,
    ContextUpgradeSafe,
    AccessControlUpgradeSafe,
    ERC721BurnableUpgradeSafe,
    ERC721PausableUpgradeSafe
{
    using Counters for Counters.Counter;

    bytes32 public constant MINTER_ROLE = keccak256("MINTER_ROLE");
    bytes32 public constant PAUSER_ROLE = keccak256("PAUSER_ROLE");

    Counters.Counter private _tokenIdTracker;

    uint256[] public planets;
    // NOTE: planetId is different with NFT ID
    mapping(uint256 => address) public planetIdToOwner;

    /**
     * @dev Grants `DEFAULT_ADMIN_ROLE` and `MINTER_ROLE`to the account that
     * deploys the contract.
     *
     * Token URIs will be autogenerated based on `baseURI` and their token IDs.
     * See {ERC721-tokenURI}.
     */

    function initialize(
        string memory name,
        string memory symbol,
        string memory baseURI
    ) public {
        __ERC721PresetMinterPauserAutoId_init(name, symbol, baseURI);
    }

    function __ERC721PresetMinterPauserAutoId_init(
        string memory name,
        string memory symbol,
        string memory baseURI
    ) internal initializer {
        __Context_init_unchained();
        __AccessControl_init_unchained();
        __ERC165_init_unchained();
        __ERC721_init_unchained(name, symbol);
        __ERC721Burnable_init_unchained();
        __Pausable_init_unchained();
        __ERC721Pausable_init_unchained();
        __ERC721PresetMinterPauserAutoId_init_unchained(name, symbol, baseURI);
    }

    function __ERC721PresetMinterPauserAutoId_init_unchained(
        string memory name,
        string memory symbol,
        string memory baseURI
    ) internal initializer {
        _setupRole(DEFAULT_ADMIN_ROLE, _msgSender());

        _setupRole(MINTER_ROLE, _msgSender());
        _setupRole(PAUSER_ROLE, _msgSender());

        _setBaseURI(baseURI);
    }

    /**
     * @notice Find the list of planetIds owned by an address
     * @param owner An address for whom the query the list of planets they own
     */
    function getPlanetIdsByOwner(address owner)
        public
        view
        returns (uint256[] memory)
    {
        uint256 ownedPlanetCounter = 0;
        for (uint256 i = 0; i < planets.length; i++) {
            if (planetIdToOwner[planets[i]] == owner) {
                ownedPlanetCounter++;
            }
        }

        uint256[] memory planetIds = new uint256[](ownedPlanetCounter);
        uint256 counter = 0;
        for (uint256 i = 0; i < planets.length; i++) {
            if (planetIdToOwner[planets[i]] == owner) {
                planetIds[counter] = planets[i];
                counter++;
            }
        }

        return planetIds;
    }

    /**
     * @dev Creates a new token for `to`. Its token ID will be automatically
     * assigned (and available on the emitted {Transfer} event), and the token
     * URI autogenerated based on the base URI passed at construction.
     *
     * See {ERC721-_mint}.
     *
     * Requirements:
     *
     * - the caller must have the `MINTER_ROLE`.
     */
    function mint(address to, uint256 planetId) public {
        require(
            hasRole(MINTER_ROLE, _msgSender()),
            "DarkForestNFT: must have minter role to mint"
        );
        require(
            planetIdToOwner[planetId] == address(0),
            "DarkForestNFT: the NFT for that planet ID have been minted"
        );

        // start housekeeping
        planets.push(planetId);
        planetIdToOwner[planetId] = to;
        // end housekeeping

        // We can just use balanceOf to create the new tokenId because tokens
        // can be burned (destroyed), so we need a separate counter.
        _mint(to, _tokenIdTracker.current());
        _tokenIdTracker.increment();
    }

    /**
     * @dev Pauses all token transfers.
     *
     * See {ERC721Pausable} and {Pausable-_pause}.
     *
     * Requirements:
     *
     * - the caller must have the `PAUSER_ROLE`.
     */
    function pause() public {
        require(
            hasRole(PAUSER_ROLE, _msgSender()),
            "DarkForestNFT: must have pauser role to pause"
        );
        _pause();
    }

    /**
     * @dev Unpauses all token transfers.
     *
     * See {ERC721Pausable} and {Pausable-_unpause}.
     *
     * Requirements:
     *
     * - the caller must have the `PAUSER_ROLE`.
     */
    function unpause() public {
        require(
            hasRole(PAUSER_ROLE, _msgSender()),
            "DarkForestNFT: must have pauser role to unpause"
        );
        _unpause();
    }

    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 tokenId
    ) internal override(ERC721UpgradeSafe, ERC721PausableUpgradeSafe) {
        super._beforeTokenTransfer(from, to, tokenId);
    }

    uint256[49] private __gap;
}
